<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create Order dan Negosiasi</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9741c57e-9476-4620-a2b6-10c55e38de0c</testSuiteGuid>
   <testCaseLink>
      <guid>1cfb3f09-ec7f-4773-a509-601f12d03b49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/Open Browser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>89bd5708-28c0-4b44-82a9-3c9676e61f3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/DirTeknis - Create Order - Normal</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25c6371e-947c-4b4c-8e3b-0a9d608d4c53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6694eb55-4e78-4bab-b24a-33afe6aafe7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48a9b3f8-3cc4-4c20-b798-1f5f16e167e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>352e9a72-80e6-44d7-86bf-f2d57ad98f2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50ea5ec-a217-4ae9-8e51-c78d943cfa50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc8b734-f0ab-40a1-ae51-ff881609ab84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2982d92-4a75-426e-beef-617940fab26e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09582581-021e-4d28-90b0-9a07190b8664</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1c0bd6d-6a8b-4916-b119-807b3b57dbfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d349778-33ce-4a6d-805c-3aeb5a230cd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3e27e80-d991-4826-8adf-14bbb61cee0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/PPK - Approve Order</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ebabed4d-3483-439d-9486-dd67af088023</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/Pengadaan - Nego Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e065c339-39d5-446f-b102-ca51666087b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056ca56c-e1db-4cda-9b19-b87e77f4e5de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f4d7561-2c40-4ea3-8f8b-915a02e1552d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/Vendor - Nego Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31db0224-3c2b-4be6-93d2-f84798871e4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be743ff3-fa4e-438a-b222-ee6c2c76d020</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abb60998-7a5b-4773-ade2-bdb1e552e334</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/Pengadaan - Nego Order Kedua</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e67f49b7-213a-4ef9-992b-c4eafd12e1b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51483c0f-910a-4d07-a5e8-c740d33868d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8915731d-52ab-4aac-986f-20c27a44fbc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/Vendor - Setujui Nego Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db1cfdc8-2744-44cb-8b72-0d5c33da8d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b83d556-3f11-423a-a9df-ece60bca1394</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df2e7da2-b283-4bd2-9572-5854be06886f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/Pengadaan - Approve Order</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ba0e1489-6039-45c9-9019-4c753bf2611c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/Vendor - Approve Order</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>47fe8e4a-dabc-403e-9200-8eed693e53f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/DirTeknis - Konfirmasi Barang</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
