<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Order is created by DirTeknis and rejected by PPK</description>
   <name>Create Order and Reject by PPK</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ed7ebd77-ab0c-4f6d-ae02-aa209d2ac512</testSuiteGuid>
   <testCaseLink>
      <guid>a33aa83f-3673-4327-8f35-921c49764e81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Transaksi/DirTeknis - Create Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fbaf6b7-e4fc-4657-a435-a71c54a10f14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30d05731-de24-4c85-8e78-9691cb52f389</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941631f5-01de-46f4-a9d4-01c3a9ef6fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97edaf0-69f4-4e49-ad6d-da3a67361166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73c0f8ca-0e9b-47ed-8e7a-f36a8c2dec4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e457a83e-b6d3-4b96-b197-662aee82cf5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe6f342e-46a2-4c97-a08a-4cee66f135f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8122e3e-b44c-4ac2-a6a6-06dd70afb671</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>071a65eb-7aee-4ae6-95db-c09e1e2772bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ecaeb70-cdb0-478d-8ee4-2fb2cf9f9183</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba16136c-7176-4850-a95d-fbdfa2524286</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/DirTeknis - Create Order - Normal</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25c6371e-947c-4b4c-8e3b-0a9d608d4c53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6694eb55-4e78-4bab-b24a-33afe6aafe7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48a9b3f8-3cc4-4c20-b798-1f5f16e167e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>352e9a72-80e6-44d7-86bf-f2d57ad98f2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50ea5ec-a217-4ae9-8e51-c78d943cfa50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc8b734-f0ab-40a1-ae51-ff881609ab84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2982d92-4a75-426e-beef-617940fab26e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09582581-021e-4d28-90b0-9a07190b8664</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1c0bd6d-6a8b-4916-b119-807b3b57dbfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d349778-33ce-4a6d-805c-3aeb5a230cd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e5a93e0-afb5-48de-80c4-2e222313741b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaksi/PPK - Reject Order</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
