<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnKembali</name>
   <tag></tag>
   <elementGuidId>c2e9a55d-0733-4bf0-9d3d-23d70964e0ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/a[contains(text(),'Kembali')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/a[contains(text(),'Kembali')]</value>
   </webElementProperties>
</WebElementEntity>
