<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popupTambahSatker</name>
   <tag></tag>
   <elementGuidId>93aba7de-7950-4515-ada8-b7be51268c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
   </webElementProperties>
</WebElementEntity>
