<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEditTelp</name>
   <tag></tag>
   <elementGuidId>cad1f82a-1f2a-4ebc-982a-76f9fcd47242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]/div/div/form//input[@placeholder='telp.']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div/div/form//input[@placeholder='telp.']</value>
   </webElementProperties>
</WebElementEntity>
