<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTelp</name>
   <tag></tag>
   <elementGuidId>0e9dddda-6db1-4c30-b97f-3fab63561b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div/div/form//input[@placeholder='telp.']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div/div/form//input[@placeholder='telp.']</value>
   </webElementProperties>
</WebElementEntity>
