<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconClose</name>
   <tag></tag>
   <elementGuidId>32537eae-ab93-4bc2-8f32-955df114e87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>*//div[4]//i[@class='icon-cancel-circle2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>*//div[4]//i[@class='icon-cancel-circle2']</value>
   </webElementProperties>
</WebElementEntity>
