<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lstJenisCategory</name>
   <tag></tag>
   <elementGuidId>815bbac9-95b7-491a-8170-af5640edfe0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select</value>
   </webElementProperties>
</WebElementEntity>
