<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnOKMap</name>
   <tag></tag>
   <elementGuidId>4ae9dab3-e002-419c-8f8d-29ac1e821412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr/td[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr/td[2]/button</value>
   </webElementProperties>
</WebElementEntity>
