<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEditUsername</name>
   <tag></tag>
   <elementGuidId>7b7f9d18-58da-4f04-ab35-1ab3212ae1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]//form/div/div/input[@placeholder='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]//form/div/div/input[@placeholder='username']</value>
   </webElementProperties>
</WebElementEntity>
