<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTambah</name>
   <tag></tag>
   <elementGuidId>2cabe8ef-b330-45ce-ac91-d382380b6f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div/form/div/div/button[contains(text(),'Tambah')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div/form/div/div/button[contains(text(),'Tambah')]</value>
   </webElementProperties>
</WebElementEntity>
