<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblChangePassword</name>
   <tag></tag>
   <elementGuidId>2270b25d-01f6-478e-b69e-030de8e715ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>*//div[3]/ul/li/div/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>*//div[3]/ul/li/div/a[1]</value>
   </webElementProperties>
</WebElementEntity>
