<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbllogout</name>
   <tag></tag>
   <elementGuidId>67854728-0117-4faf-8132-bb0b2a1aac94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>*//li//a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>*//li//a[2]</value>
   </webElementProperties>
</WebElementEntity>
