<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconClose</name>
   <tag></tag>
   <elementGuidId>c0446ac1-ac88-4c7c-ae05-6540b15e6f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]/div/div/div/button/i[@class='icon-cancel-circle2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button/i[@class='icon-cancel-circle2']</value>
   </webElementProperties>
</WebElementEntity>
