<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConfirmNego</name>
   <tag></tag>
   <elementGuidId>89e7216c-5f1d-442b-9f40-ff46d9c6351d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
