<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblNegoPricefrVendor</name>
   <tag></tag>
   <elementGuidId>7094fbf2-8906-4193-8ebc-eea04f39d033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[1]/li/div[2]//span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[1]/li/div[2]//span/b</value>
   </webElementProperties>
</WebElementEntity>
