<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lstPaymentMethod</name>
   <tag></tag>
   <elementGuidId>ef88cf10-33a5-4742-ab3b-30833d0d9390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select</value>
   </webElementProperties>
</WebElementEntity>
