<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEditTeleponAgen</name>
   <tag></tag>
   <elementGuidId>552b0be8-1134-454d-a99e-83f011cbb8db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]/div/div/form//input[@placeholder='telepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div/div/form//input[@placeholder='telepon']</value>
   </webElementProperties>
</WebElementEntity>
