<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTelepon</name>
   <tag></tag>
   <elementGuidId>364b1413-069d-4516-885a-8e51afe9165f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]//form/div//input[@placeholder='telepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]//form/div//input[@placeholder='telepon']</value>
   </webElementProperties>
</WebElementEntity>
