<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconClose</name>
   <tag></tag>
   <elementGuidId>6e230e10-ffc0-4fc1-8d95-b809151c32e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]//i[@class='icon-cancel-circle2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]//i[@class='icon-cancel-circle2']</value>
   </webElementProperties>
</WebElementEntity>
