<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconClose</name>
   <tag></tag>
   <elementGuidId>6a86e95d-7077-4a9e-8161-ab84e8d74424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]//i[@class='icon-cancel-circle2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]//i[@class='icon-cancel-circle2']</value>
   </webElementProperties>
</WebElementEntity>
