<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblStatusOrder</name>
   <tag></tag>
   <elementGuidId>6b67781b-0ed1-4ee6-9bf0-39256fa86961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td/span[contains(text(),'Order')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td/span[contains(text(),'Order')]</value>
   </webElementProperties>
</WebElementEntity>
