<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtAlamatDistributor</name>
   <tag></tag>
   <elementGuidId>85788492-885c-4a7a-ac38-04d38252239e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div/div/form/div/div/textarea[@placeholder='alamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div/textarea[@placeholder='alamat']</value>
   </webElementProperties>
</WebElementEntity>
