<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEditNamaDistributor</name>
   <tag></tag>
   <elementGuidId>78a495e0-748c-42ed-945a-ad4fe92a8e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]/div/div/form/div/div//input[@placeholder='nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div/div//input[@placeholder='nama']</value>
   </webElementProperties>
</WebElementEntity>
